### ISSUE TITLE
Create new set of use cases

### ISSUE THREAD

**Issue by Incnas** [ANU-Linked-Earth-Data/main-repo#11]
Hopefully from our meeting at GA, and with other potential users and related persons, we can create a well formed set of potential use cases that we see this implementation being applicable to.

**Comment by Incnas** [comment]
Maybe this along with the other feature document should be publicly available on github?

**Comment by dmitry-brizhinev** [comment]
https://github.com/ANU-Linked-Earth-Data/use-cases/blob/master/use-cases.md
