### ISSUE TITLE
How to organise our stuff

### ISSUE THREAD

**Issue by mikeplus64** [ANU-Linked-Earth-Data/main-repo#4]
I suggest having our own git repos (but still under the github organisation) that we just put as git submodules here. That's a pretty popular way of organisating large git repositories, and I think pretty essential for ones that have lots of binary data (which git isn't renown for handling very well). e.g. https://github.com/ghc/ghc/tree/master/libraries https://github.com/red-eclipse/base/tree/master/data

**Comment by Incnas** [comment]
I like the idea. Although alternatively, if large testing data is the issue. We can host that in another location or another repository while still keeping this one as the sole code repository. However, if you feel code should also be separated then I'd be happy to use multiple repositories.

**Comment by mikeplus64** [comment]
The main motivation is just to separate each independent component, they get their own issue tracking and wikis that way. It's just easier to develop with since you won't have to git pull (or even merge? to get code that isn't your concern/from a different module) before making commits.

**Comment by Incnas** [comment]
Fair enough. I'm happy with multiple repos. I'll set that up after the monday meeting in case there's any major objections, just to run through a formal decision process.

**Comment by Incnas** [comment]
Now using a repository for each section of the project.
