### ISSUE TITLE
Poster (5 marks, due April 1)

### ISSUE THREAD

**Issue by qxcv** [ANU-Linked-Earth-Data/main-repo#6]
Quoted from [here](https://anutechlauncher.net/projects/course-guide-2016-s1/wiki/Poster_1_%285_marks%29):

>  The aim of the first poster is to show that your team understands your project and that you can communicate that understanding in a concise and effective manner.
>
> The poster should summarise:
> 
> - Project context - client or market, current situation, need for new system
> - Concept for new system - architecture, functions, processes
> - Expected impact of new system

Due at 1700 on Friday, Week 7 (first semester).

**Comment by Incnas** [comment]
I think we should use a powerpoint like in R&D last year. I've put a ppt up here: https://drive.google.com/open?id=0B__rn__7FvrsR3BfbGNXWEJYV1U
