### ISSUE TITLE
Internal presentation (unmarked, indirectly affects later assessment)

### ISSUE THREAD

**Issue by qxcv** [ANU-Linked-Earth-Data/main-repo#7]
The "[internal project presentations](https://anutechlauncher.net/projects/course-guide-2016-s1/wiki/Internal_Project_Presentations_%2820_marks%29)" assessment item is worth 20 marks all up, and consists of a slide deck and presentation prepared by the whole team (0 marks) along with an individual report about your presentation and the other groups' presentations. Quoted from aforementioned page:

> During Week 7 of each Semester we will run a series of project presentation sessions. Each session will run for two hours and will comprise presentations by 4 project teams. Every team will be required to attend and must present in one of these sessions.
>
> Each team's presentation will cover the topics listed in the TechLauncher Project Review Rubric (see Sample Project Review Rubric):
>
> - Planning and project management
> - Software engineering practice
> - Progress
> - Software engineering environment
> - Stakeholder relationships
> - Teamwork
>
> The aim of this activity is to help teams understand and reflect on their own performance relative to several other TechLauncher project teams.
>
> ### Team Slides
>
> Each team must submit their slides (as a PDF) using Wattle by 1700 the day before their presentation. This will allow us to pre-load the slides to ensure smooth operation on the day of your presentation.
>
> ### Individual Report
>
> The actual presentations will not be assessed. Instead, every student is required to attend the entire session in which they present each semester. After each session, each student must submit an individual report comprising the following items:
>
> - A completed Project Review Rubric for each team that presented in the session (excluding their own). Note that these completed rubrics will be provided anonymously to the teams involved.
> - Two pages outlining lessons from each project that can be applied to your project and why these would help
> - A reflective piece on how your project is proceeding relative to the others in your session and what your team should do to improve it's performance.

Slides are due at 1700 on day before presentation, report is due Monday Week 8.

**Comment by Incnas** [comment]
Powerpoint was submitted on time.

**Comment by qxcv** [comment]
Team component of this is done, so issue doesn't need to be open any longer.
